export { default as Home } from './home/Home'
export { default as About } from './about/About'
export { default as Experience } from './experience/Experience'
export { default as Work } from './work/Work'
export { default as Contact } from './contact/Contact'